version: "3.9"

services:
  gateway:
    build:
      context: ./apps/gateway-api
      dockerfile: Dockerfile
    environment:
      ORCHESTRATOR_URL: http://orchestrator:4000
      INDEXER_URL: http://indexer:7071
      PORT: "8080"
      GATEWAY_SSE_MAX_CONNECTIONS_PER_IP: "4"
      GATEWAY_MAX_REQUEST_BODY_BYTES: ${GATEWAY_MAX_REQUEST_BODY_BYTES:-1048576}
      OAUTH_ALLOW_INSECURE_STATE_COOKIE: "true"
    ports:
      - "8080:8080"
    depends_on:
      - orchestrator
    restart: unless-stopped

  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: "4000"
      RUN_MODE: consumer
      REDIS_URL: redis://redis:6379/0
      POSTGRES_URL: postgres://ossaat:ossaat@postgres:5432/ossaat
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      KAFKA_BROKERS: kafka:9092
      POSTGRES_MIN_CONNECTIONS: ${POSTGRES_MIN_CONNECTIONS:-2}
      POSTGRES_STATEMENT_TIMEOUT_MS: ${POSTGRES_STATEMENT_TIMEOUT_MS:-5000}
      POSTGRES_QUERY_TIMEOUT_MS: ${POSTGRES_QUERY_TIMEOUT_MS:-5000}
      LANGFUSE_BASE_URL: http://langfuse:3000
      LANGFUSE_PUBLIC_KEY: dev-public
      LANGFUSE_SECRET_KEY: dev-secret
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      PROMETHEUS_URL: http://prometheus:9090
      LOCAL_SECRETS_PASSPHRASE: ${LOCAL_SECRETS_PASSPHRASE:-dev-local-passphrase}
      LOCAL_SECRETS_PATH: ${LOCAL_SECRETS_PATH:-/app/config/secrets/local/secrets.json}
      SSE_MAX_CONNECTIONS_PER_IP: "4"
      SSE_MAX_CONNECTIONS_PER_SUBJECT: "2"
      SERVER_REQUEST_LIMIT_JSON_BYTES: "1048576"
      SERVER_REQUEST_LIMIT_URLENCODED_BYTES: "1048576"
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres
      - rabbitmq
      - kafka
    restart: unless-stopped

  indexer:
    build:
      context: ./services/indexer
      dockerfile: Dockerfile
    environment:
      RUST_LOG: info
      INDEXER_MAX_REQUEST_BODY_BYTES: "1048576"
      RUN_MODE: ${RUN_MODE:-consumer}
      INDEXER_JWT_HS256_SECRET: ${INDEXER_JWT_HS256_SECRET:-dev-indexer-secret}
      INDEXER_JWT_ISSUER: ${INDEXER_JWT_ISSUER:-http://orchestrator:4000}
      INDEXER_JWT_AUDIENCE: ${INDEXER_JWT_AUDIENCE:-oss-ai-indexer}
      DATABASE_URL: postgres://ossaat:ossaat@postgres:5432/ossaat
      HF_ENDPOINT: https://huggingface.co
      GIT_REPO_PATH: /repo
      INDEXER_LISTEN_ADDR: 0.0.0.0:7071
      INDEXER_GRPC_ADDR: 0.0.0.0:7070
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    depends_on:
      - postgres
    ports:
      - "7070:7070"
      - "7071:7071"
    volumes:
      - .:/repo
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:7.2.0-v9
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      POSTGRES_USER: ossaat
      POSTGRES_PASSWORD: ossaat
      POSTGRES_DB: ossaat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
      - /var/run/postgresql

  rabbitmq:
    image: rabbitmq:3.13-management
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    tmpfs:
      - /tmp

  kafka:
    image: apache/kafka:3.7.0
    security_opt:
      - no-new-privileges:true
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    tmpfs:
      - /tmp

  jaeger:
    image: jaegertracing/all-in-one:1.57
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    tmpfs:
      - /tmp

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  langfuse:
    image: langfuse/langfuse:2
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      DATABASE_URL: postgres://ossaat:ossaat@postgres:5432/ossaat
      NEXTAUTH_SECRET: dev-secret
      NEXTAUTH_URL: http://localhost:3000
      SALT: dev-salt
      TELEMETRY_ENABLED: "false"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - langfuse-data:/app/.langfuse
    tmpfs:
      - /tmp

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  kafka-data:
  langfuse-data:
